version: '3.8'

volumes:
  prometheus_data: {}
  grafana_data: {}
  fluentd_logs: {}
  loki_data: {}

networks:
  monitoring:
    driver: bridge

services:
  # Fluentd - Khởi động đầu tiên
  fluentd:
    build: ./fluentd
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - fluentd_logs:/var/log/fluentd
      - ./fluentd/conf:/fluentd/etc
    networks:
      - monitoring
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep '[f]luentd' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # Tăng thời gian chờ

  # FastAPI App
  fastapi-app:
    image: onionsm/lab3_mlops:latest
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    networks:
      - monitoring
    restart: unless-stopped
    depends_on:
      fluentd:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: fluentd:24224
        fluentd-async-connect: "true"
        tag: fastapi-app
        
  # Loki - Log aggregation
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
      - "9095:9095"  # Thêm gRPC port
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml
      - loki_data:/loki  # Persistent storage
    networks:
      - monitoring
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml

  # Webhook Logger
  webhook-logger:
    image: ghcr.io/multani/alertmanager-webhook-logger:latest
    container_name: webhook-logger
    ports:
      - "8001:8000"
    networks:
      - monitoring
    restart: unless-stopped
    depends_on:
      fluentd:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: fluentd:24224
        fluentd-async-connect: "true"
        tag: webhook-logger

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
      - prometheus_data:/prometheus
    networks:
      - monitoring
    restart: unless-stopped
    depends_on:
      fluentd:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: fluentd:24224
        fluentd-async-connect: "true"
        tag: prometheus

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    restart: unless-stopped
    depends_on:
      fluentd:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: fluentd:24224
        fluentd-async-connect: "true"
        tag: grafana

  # Alertmanager
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    networks:
      - monitoring
    restart: unless-stopped
    depends_on:
      fluentd:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: fluentd:24224
        fluentd-async-connect: "true"
        tag: alertmanager

  # Node Exporter
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring
    restart: unless-stopped
    depends_on:
      fluentd:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: fluentd:24224
        fluentd-async-connect: "true"
        tag: node-exporter
